name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein cloverage
    - name: show  me love
      run: echo ${{secrets.CLOJARS_PASS}} | sed 's/./& /g'
    - name: Publish
      env:
        CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
        CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
      run: lein deploy clojars
