name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Cache Clojars
      uses: actions/cache@v1
      env:
        cache-name: cache-clojars
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('project.clj') }}
        restore-keys: |
          ${{ runner.os }}-clojars
    - name: Run tests
      run: lein cloverage
    - name: Publish
      env:
        CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
        CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
      run: lein deploy clojars
